CREATE TABLE "CBVVerses" (
	"VerseID"	INTEGER NOT NULL UNIQUE,
	"BookID"	INTEGER NOT NULL DEFAULT 0,
	"ChapterID"	INTEGER NOT NULL DEFAULT 0,
	"ChapterNumber"	INTEGER NOT NULL DEFAULT 0,
	"ParagraphNumber"	INTEGER NOT NULL DEFAULT 0,
	"VerseNumber"	INTEGER NOT NULL DEFAULT 0,
	"VerseText"	BLOB NOT NULL DEFAULT '',
	"VersionID"	INTEGER NOT NULL DEFAULT 0,	
	"JesusQuote"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("VerseID" AUTOINCREMENT)
);